version: "3"

services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: 'gunot-webserver'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-./src}:/var/www/html:z
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini:z
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled:z
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2:z
  mysql:
    build:
      context: "./bin/${DATABASE}"
    container_name: 'gunot-mysql'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql:z
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql:z
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}